name: goalmoney_fe
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1

  # Networking
  dio: ^5.3.3

  # Local Storage (for Token)
  shared_preferences: ^2.2.2

  # Image Picker
  image_picker: ^1.1.2

  # Path Provider
  path_provider: ^2.1.2

  # Formatting
  intl: ^0.19.0

  # Firebase
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^18.0.1

  # Share
  share_plus: ^10.0.0

  # PDF & Excel Export
  pdf: ^3.11.0
  printing: ^5.13.0
  excel: ^4.0.6
  open_file: ^3.5.7

  # Charts
  fl_chart: ^0.69.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
